import Logo from "@/components/Logo";

export const metadata = {
  title: "Frequently Asked Questions",
  description:
    "Answers about swapping crypto on TokensFund without KYC: how non-custodial swaps work, supported assets and protocols, the 2% fee, safety, and privacy.",
  keywords: [
    "tokensfund faq",
    "no KYC crypto swap faq",
    "non custodial swap questions",
    "crypto swap fees",
    "is tokensfund safe",
  ],
  alternates: { canonical: "/faq" },
  openGraph: {
    type: "website",
    url: "/faq",
    title: "TokensFund FAQ — No-KYC Crypto Swaps",
    description:
      "How non-custodial swaps work, which protocols and assets are supported, the 2% fee, safety, and privacy — answered.",
    images: [
      {
        url: "https://tokensfund.xyz/og-image.png",
        width: 1200,
        height: 630,
        alt: "TokensFund — Frequently Asked Questions",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "TokensFund FAQ — No-KYC Crypto Swaps",
    description:
      "How non-custodial swaps work, which protocols and assets are supported, the 2% fee, safety, and privacy — answered.",
    images: ["https://tokensfund.xyz/og-image.png"],
  },
};

// Single source of truth: the visible FAQ and the JSON-LD schema are both built
// from this array, so they can never fall out of sync.
const faqs = [
  {
    section: "The basics",
    q: "What is TokensFund?",
    a: "TokensFund is a non-custodial cross-chain swap aggregator. Instead of giving you a single exchange's price, it compares live quotes from five routing protocols and sends your swap through whichever offers the best rate. There's no account, no sign-up, and no KYC, and your funds never pass through us.",
  },
  {
    section: "The basics",
    q: "Do I need an account or to complete KYC?",
    a: "No. There's no account, no email, and no identity verification. You enter what you want to swap, get a one-time deposit address, send from your own wallet, and receive in your own wallet.",
  },
  {
    section: "The basics",
    q: "Which assets can I swap?",
    a: "TokensFund supports 15+ assets across multiple chains, including BTC, ETH, XMR, SOL, XRP, DOGE, LTC, TON, NEAR, and USDC and USDT on Ethereum and Tron. The full, current list is always shown in the swap dropdown on the homepage.",
  },
  {
    section: "The basics",
    q: "Which protocols does TokensFund route through?",
    a: "TokensFund compares and routes across five protocols: THORChain, Chainflip, NEAR Intents, Changee, and CCE.Cash. You always see which route a quote comes from before you confirm. The swap itself is executed by the underlying protocol — TokensFund is the comparison and routing layer on top.",
  },
  {
    section: "Using TokensFund",
    q: "How does a swap work, step by step?",
    a: "Choose the asset you're sending and the one you want to receive, enter the amount along with your destination and refund addresses, then compare the live quotes. Pick the best route to generate a one-time deposit address, send the funds from your own wallet as a normal on-chain transfer, and the swapped asset arrives directly in your destination wallet.",
  },
  {
    section: "Using TokensFund",
    q: "Why do you ask for both a destination address and a refund address?",
    a: "The destination address is where your swapped crypto is delivered. The refund address is where your original funds are returned if a swap can't complete — for example, if the rate moves too far or a network fails. Both are required so that, whatever happens, your funds end up in a wallet you control.",
  },
  {
    section: "Using TokensFund",
    q: "How long does a swap take?",
    a: "It depends on the assets and networks involved and on confirmation times on each chain. Most swaps finish within minutes, though slower or congested networks can take longer. You can follow live status on the Track page.",
  },
  {
    section: "Using TokensFund",
    q: "Can I track a swap in progress?",
    a: "Yes. Paste your deposit address or tracking ID into the Track page and select the provider you used. Live status depends on each provider's own system, so some swaps may show as unavailable until funds are sent.",
  },
  {
    section: "Trust & safety",
    q: "Is TokensFund custodial? Do you ever hold my funds?",
    a: "No. TokensFund is fully non-custodial. You send to a one-time deposit address generated by the routing protocol and receive at your own wallet. At no point do we take custody of, hold, or have access to your assets.",
  },
  {
    section: "Trust & safety",
    q: "Is it safe? What are the risks?",
    a: "The custody risk that affects most exchanges doesn't apply here, because we never hold your money. But cross-chain swaps still carry real risks: sending the wrong asset or using the wrong network can cause loss, quoted rates can move slightly with market conditions and liquidity before a swap executes, and each routing protocol carries its own smart-contract and liquidity risk. If a swap can't complete, your funds are returned to your refund address. No swap is risk-free, so always double-check the asset, network, and amount before sending.",
  },
  {
    section: "Trust & safety",
    q: "What happens if a swap fails or I send the wrong amount?",
    a: "If a swap can't be completed, your original funds are sent back to the refund address you provided, minus unavoidable network fees. Sending an amount far from your quote, or on the wrong network, can cause a swap to fail — and sending on the wrong chain can result in lost funds — so check the deposit asset, network, and amount carefully before sending.",
  },
  {
    section: "Trust & safety",
    q: "Who is behind TokensFund?",
    a: "TokensFund is built by a small independent team focused on one thing: a thin, honest aggregation layer over established swap protocols. We're reachable on X and Telegram. By design we hold none of your funds and collect none of your identity, so using TokensFund doesn't require trusting us with custody — the protocols do the swapping; we just find you the best route.",
  },
  {
    section: "Fees & rates",
    q: "How does TokensFund make money? Do you charge a fee?",
    a: "TokensFund charges a flat 2% fee per swap, and it's already included in the rate you see before you confirm. There's no separate charge added at the end — the quoted output is what lands in your wallet. The quote reflects everything: the routing protocol's costs and our 2% fee.",
  },
  {
    section: "Fees & rates",
    q: "Will I get exactly the rate I'm quoted?",
    a: "Quotes are live estimates, not locked guarantees. The amount you actually receive can move slightly with network conditions and the routing protocol's liquidity between the moment you get the quote and the moment the swap executes. The 2% TokensFund fee is already built into the quote, so review the figure on screen before sending.",
  },
  {
    section: "Fees & rates",
    q: "Are there minimum or maximum swap amounts?",
    a: "No. TokensFund doesn't set minimum or maximum swap limits — you can swap any amount. Keep in mind that on very small swaps, network fees can take a meaningful bite out of the value, so extremely tiny amounts may not be worth it.",
  },
  {
    section: "Privacy & legal",
    q: "What data do you collect?",
    a: "No account, no email, no ID. We don't store your identity or your wallet balances. We process only the minimal technical information needed to fetch quotes and run the service.",
  },
  {
    section: "Privacy & legal",
    q: "Is using TokensFund legal?",
    a: "Using non-custodial swap tools is permitted in most places, but laws and tax rules vary by jurisdiction. You're responsible for complying with the rules where you live, including any tax obligations on your swaps. TokensFund is a routing interface, not a financial or legal advisor, and nothing here is financial or legal advice.",
  },
  {
    section: "Privacy & legal",
    q: "Do you report swaps to any authority?",
    a: "TokensFund doesn't collect the identity information that reporting would require, and it isn't a custodial exchange. Responsibility for any tax reporting on your own activity rests with you. Crypto-to-crypto swaps are taxable events in most countries regardless of the platform used.",
  },
];

const sections = Array.from(new Set(faqs.map((f) => f.section)));

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((f) => ({
    "@type": "Question",
    name: f.q,
    acceptedAnswer: { "@type": "Answer", text: f.a },
  })),
};

const brandStyle = { textDecoration: "none", color: "inherit" };

const ctaStyle = {
  display: "inline-block",
  textDecoration: "none",
  background: "var(--gold)",
  color: "#000",
  fontWeight: "700",
  padding: "12px 28px",
  borderRadius: "8px",
  fontSize: "1rem",
};

export default function FAQ() {
  return (
    <main className="wrap">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />

      <header className="masthead">
        <div className="header-inner">
          <a href="/" className="brand" style={brandStyle}>
            <Logo size={34} />
            <span>tokensfund<span className="tld">.xyz</span></span>
          </a>
          <nav className="main-nav">
            <a href="/" className="nav-link">Swap</a>
            <a href="/track" className="nav-link">Track</a>
            <a href="/blog" className="nav-link">Blog</a>
          </nav>
        </div>
      </header>

      <article className="blog-post">
        <h1>Frequently Asked Questions</h1>
        <p>
          Everything you need to know about swapping with TokensFund — no account required.
        </p>

        {sections.map((section) => (
          <section key={section}>
            <h2>{section}</h2>
            {faqs
              .filter((f) => f.section === section)
              .map((f) => (
                <div key={f.q} className="faq-item">
                  <h3>{f.q}</h3>
                  <p>{f.a}</p>
                </div>
              ))}
          </section>
        ))}

        <div className="blog-cta">
          <p>Ready to swap, no account needed?</p>
          <a href="/" style={ctaStyle}>
            Swap Now at TokensFund
          </a>
        </div>
      </article>
    </main>
  );
}
